problems_list/urls.py
from django.urls import path
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from . import views

app_name = 'problems_list'
urlpatterns = [
    path( 
        '', 
        views.problems_list, 
        name='home'
    ),
    path( 
        'search/', 
        views.search, 
        name='search'
    ),
    path( 
        '<int:pk>/', 
        views.note, 
        name = 'note'
    ),
    path( 
        'about/', 
        views.about, 
        name = 'about'
    ),
    # path(
    #     'add/',
    #     views.add,
    #     name = 'add'
    # ),
    path(
        'favicon.ico',
        RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico')),
        name = 'favicon'
    ),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('problems_list.urls')),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

problems_list/models.py
from django.db import models


class Difficulty(models.Model):
    name = models.CharField(max_length=7, null=True)

    def __str__(self):
        return self.name
        

class Problem(models.Model):
    difficulty  = models.ForeignKey(Difficulty, on_delete=models.CASCADE)
    name        = models.CharField(max_length=256, null=True)
    topic       = models.CharField(max_length=256, null=True)
    add_date    = models.DateTimeField(auto_now_add=True)
    link        = models.URLField(max_length=256, null=True, unique=True)
    note        = models.TextField(null=True)
    source_code = models.FileField(upload_to='source_code/', null=True, default=None, blank=True)

    def __str__(self):
        return self.name


class Links(models.Model):
    name = models.CharField(max_length=256, null=True)
    url  = models.URLField(max_length=256, unique=True, blank=True)

    def __str__(self):
        return self.name

problems_list/forms.py
from django import forms
from django.forms import ModelForm
from .models import Problem

class ProblemForm(ModelForm):
    class Meta:
        model = Problem
        fields = (
            'name', 
            'topic', 
            'difficulty', 
            'link', 
            'note', 
            'source_code'
        )

problems_list/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from .utils.problems_list.paginate import try_page
from .models import Problem
from .forms import ProblemForm


def problems_list(request):
    problems_list = Problem.objects.all().order_by('-add_date')
    problems_count = problems_list.count()
    
    problems = try_page(request, problems_list)

    context = {
        'problems': problems,
        'problems_count': problems_count,
    }
    return render(request, 'problems_list/list.html', context)


def search(request):
    query = request.GET.get('q') if request.GET.get('q') != None else ''

    problems_list = Problem.objects.filter(
        Q(name__icontains=query) |
        Q(topic__icontains=query) |
        Q(difficulty__name__icontains=query)
    ).order_by('-add_date')

    problems_count = problems_list.count()

    problems = try_page(request, problems_list)

    context = {
        'problems': problems,
        'problems_count': problems_count,
        'query': query,
    }

    return render(request, 'problems_list/search.html', context)


def note(request, pk):
    problem = Problem.objects.get(id=pk)

    context = {
        'problem': problem,
    }
    return render(request, 'problems_list/note.html', context)


def about(request):
    return render(request, 'problems_list/about.html')


# def add(request):
#     form = ProblemForm

#     if request.method == 'POST':
#         form = ProblemForm(request.POST, request.FILES)

#         if form.is_valid():
#             form.save()
#             return redirect('home')

#     context = {
#         'form': form
#     }
#     return render(request, 'problems_list/add.html', context)

problems_list/templates/problems_list/about.html
{% extends 'base.html' %} 
{% load static %} 

{% block title %}
  <title>About</title>
{% endblock title %} 

{% block content %} 
  <div class="container">
    <div class="row">
      <div class="col-sm-8">
        <p>This is where I put all my solved leetcode problems, notes, and source codes.</p>
      </div>
      
      <div class="col-sm-4 back-to-home">
        <a href="{% url 'problems_list:home' %}">&larr; Back to dashboard</a>
      </div>
    </div>
  </div>
{% endblock content %}

problems_list/templates/problems_list/add.html
{% extends 'base.html' %} 
{% load static %} 

{% block title %}
  <title>Add a problem</title>
{% endblock title %}

{% block content %}
  <div class="container">
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %} 
      {{ form.as_p }}
      <input type="submit" class="btn btn-success" />
    </form>
  </div>
{% endblock content %}

problems_list/templates/problems_list/chart.html
{% block script %}
  <!-- Chart.js CDN  -->
  <script src="https://cdn.jsdelivr.net/npm/chart.js@3.9.1/dist/chart.min.js"></script>
{% endblock script %}

<canvas id="problemsStatChart"></canvas>

<script>
  const easy_total = '{{ easy_count }}';
  const medium_total = '{{ medium_count }}';
  const hard_total = '{{ hard_count }}';

  const ctx = document.getElementById('problemsStatChart').getContext('2d');
  const myChart = new Chart(ctx, {
    type: 'pie',
    data: {
      labels: [' Easy', ' Medium', ' Hard'],
      datasets: [{
        label: 'problems',
        data: [easy_total, medium_total, hard_total],
        backgroundColor: [
          'rgba(0, 128, 0, 0.6)',
          'rgba(255, 165, 0, 0.6)',
          'rgba(255, 0, 0, 0.6)'
        ],
        borderColor: [
          'rgba(255, 255, 255, 1)',
          'rgba(255, 255, 255, 1)',
          'rgba(255, 255, 255, 1)'
        ],
        hoverOffset: 4,
        borderAlign: 'inner',
        borderWidth: 1
      }]
    }
  });
</script>

problems_list/templates/problems_list/list.html
{% extends 'base.html' %} 
{% load static %}

{% block title %}
  <title>LeetCode Dashboard</title>
{% endblock title %} 

{% block content %}
  <div class="my-container">
    {% include 'problems_list/topbar.html' %}
    <div class="row">
      <div class="col-sm-2 sidebar">
        <ul>
          <li>
            {% csrf_token %}
            <form method="GET" 
              action="search" 
              autocomplete="off" 
              style="display: flex; justify-content: space-around;">

              <input name="q" id="q"
                class="form-control" 
                type="search" 
                placeholder="Search..." 
                aria-label="Search"
              />
              <button type="submit" class="submit-btn">&#x1F50E;&#xFE0E;</button>
            </form>
          </li>
          {% include 'problems_list/sidebar.html' %}
        </ul>
      </div>

      <div class="col-sm-7 problems-list" >
        <section class="problems-count">
            Total {{ problems_count }} problems
        </section>
        
        <table>
          <tr>
            <th>Problem</th>
            <th>Topic</th>
            <th>Difficulty</th>
            <th>Solution Note</th>
            <th>Source Code</th>
          </tr>
          {% for problem in problems %}
            <tr>
              <td>
                <a href="{{ problem.link }}" target="blank" rel="noopener noreferrer">
                  {{ problem.name }}
                </a>
              </td>
              <td class="problem-topic">
                {{ problem.topic }}
              </td>
              <td class="{{ problem.difficulty }}">
                {{ problem.difficulty }}
              </td>
              <td>
                <a class="problem-note" href="{% url 'problems_list:note' problem.id %}">
                  Note
                </a>
              </td>
              <td>
                {% if problem.source_code %}
                  <a class="problem-code" href="{{ problem.source_code.url }}">
                    Python
                  </a>
                {% else %}
                  no file
                {% endif %}
              </td>
            </tr>
          {% endfor %}
        </table>
        <div class="space"></div>
        {% include  'problems_list/paginator.html'%}
      </div>
      
      <div class="col-sm-3 sidebar">
        {% include 'problems_list/chart.html' %}
      </div>
    </div>
  </div>
{% endblock content %}

problems_list/templates/problems_list/note.html
{% extends 'base.html' %} 
{% load static %} 
{% load problems_list_extras %} 

{% block link %}
  <!-- Need this for code highlighting -->
  <link rel="stylesheet" href="{% static 'css/default.css' %}" />
{% endblock link %} 

{% block title %}
  <title>{{ problem.name }}</title>
{% endblock title %} 

{% block content %} 
  <div class="container">
    <div class="row">
      <div class="col-sm-8">
        {{ problem.note|convert_markdown|safe }}
      </div>

      <div class="col-sm-4 back-to-home">
        <a href="{% url 'problems_list:home' %}">&larr; Back to dashboard</a>
      </div>
    </div>
  </div>
{% endblock content %}

problems_list/templates/problems_list/paginated_search.html
{% if problems.has_other_pages %}
  <nav>
    <ul class="pagination justify-content-center">
      {% if problems.has_previous %}
        <li class="page-item">
          <a class="page-link" 
            style="color: #000000;"
            href="?q={{ query }}&page={{ problems.previous_page_number }}" 
            aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
            <span class="page-link" aria-hidden="true">&laquo;</span>
        </li>
      {% endif %}

      {% for p in problems.paginator.page_range %}
        {% if problems.number == p %}
          <li class="page-item">
            <a class="page-link" 
              style="background-color: #d7edff; color: black;" 
              href="#">
              {{ p }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" 
              style="color: black;"
              href="?q={{ query }}&page={{ p }}">
              {{ p }}
            </a>
          </li>
        {% endif %}
      {% endfor %}

      {% if problems.has_next %}
        <li class="page-item">
          <a class="page-link" 
            style="color: #000000;"
            href="?q={{ query }}&page={{ problems.next_page_number }}" 
            aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link" aria-hidden="true">&raquo;</span>
        </li>
      {% endif %}
  </ul>
  </nav>
{% endif %}

problems_list/templates/problems_list/paginator.html
{% if problems.has_other_pages %}
  <nav>
    <ul class="pagination justify-content-center">
      {% if problems.has_previous %}
        <li class="page-item">
          <a class="page-link" 
            style="color: black;"
            href="?page={{ problems.previous_page_number }}" 
            aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
            <span class="page-link" aria-hidden="true">&laquo;</span>
        </li>
      {% endif %}

      {% for p in problems.paginator.page_range %}
        {% if problems.number == p %}
          <li class="page-item">
            <a class="page-link" 
              style="background-color: #d7edff; color: black;" 
              href="#">
              {{ p }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" 
              style="color: black;"
              href="?page={{ p }}">
              {{ p }}
            </a>
          </li>
        {% endif %}
      {% endfor %}

      {% if problems.has_next %}
        <li class="page-item">
          <a class="page-link" 
            style="color: black;"
            href="?page={{ problems.next_page_number }}" 
            aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link" aria-hidden="true">&raquo;</span>
        </li>
      {% endif %}
  </ul>
  </nav>
{% endif %}

problems_list/templates/problems_list/paginator_search.html
{% if problems.has_other_pages %}
  <nav>
    <ul class="pagination justify-content-center">
      {% if problems.has_previous %}
        <li class="page-item">
          <a class="page-link" 
            style="color: #000000;"
            href="?q={{ query }}&page={{ problems.previous_page_number }}" 
            aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
            <span class="page-link" aria-hidden="true">&laquo;</span>
        </li>
      {% endif %}

      {% for p in problems.paginator.page_range %}
        {% if problems.number == p %}
          <li class="page-item">
            <a class="page-link" 
              style="background-color: #d7edff; color: black;" 
              href="#">
              {{ p }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" 
              style="color: black;"
              href="?q={{ query }}&page={{ p }}">
              {{ p }}
            </a>
          </li>
        {% endif %}
      {% endfor %}

      {% if problems.has_next %}
        <li class="page-item">
          <a class="page-link" 
            style="color: #000000;"
            href="?q={{ query }}&page={{ problems.next_page_number }}" 
            aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link" aria-hidden="true">&raquo;</span>
        </li>
      {% endif %}
  </ul>
  </nav>
{% endif %}

problems_list/templates/problems_list/search.html
{% extends 'base.html' %} 
{% load static %}

{% block title %}
  <title>Leetcode Problems List</title>
{% endblock title %} 

{% block content %}
  <div class="my-container">
    {% include 'problems_list/topbar.html' %}
    <div class="row">
      <div class="col-sm-2 sidebar">
        <ul>
          {% include 'problems_list/sidebar.html' %}
        </ul>
      </div>

      <div class="col-sm-7 problems-list" >
        <section class="problems-count">
            Total {{ problems_count }} problems
        </section>
        
        <table>
          <tr>
            <th>Problem</th>
            <th>Topic</th>
            <th>Difficulty</th>
            <th>Solution Note</th>
            <th>Source Code</th>
          </tr>
          {% for problem in problems %}
            <tr>
              <td>
                <a href="{{ problem.link }}" target="blank" rel="noopener noreferrer">
                  {{ problem.name }}
                </a>
              </td>
              <td class="problem-topic">
                {{ problem.topic }}
              </td>
              <td class="{{ problem.difficulty }}" >
                {{ problem.difficulty }}
              </td>
              <td>
                <a class="problem-note" href="{% url 'problems_list:note' problem.id %}">
                  Note
                </a>
              </td>
              <td>
                {% if problem.source_code %}
                  <a class="problem-code" href="{{ problem.source_code.url }}">
                    Python
                  </a>
                {% else %}
                  no file
                {% endif %}
              </td>
            </tr>
          {% endfor %}
        </table>
        <div class="space"></div>
        {% include  'problems_list/paginator_search.html'%}
      </div>
      
      <div class="col-sm-3 sidebar">
        {% include 'problems_list/chart.html' %}
      </div>
    </div>
  </div>
{% endblock content %}

problems_list/templates/problems_list/sidebar.html
<li class="nav-item">
  <a href="{% url 'problems_list:about' %}">About</a>
</li>
<li class="nav-item">
  <a href="{{ leetcode_github.url }}" target="_blank" rel="noopener noreferrer">
    GitHub
  </a>
</li>
<li class="nav-item">
  <a href="{% url 'admin:index' %}" target="_blank" rel="noopener noreferrer">Admin</a>
</li>

problems_list/templates/problems_list/topbar.html
<div class="row">
  <div class="col-sm-12 topbar">
    <ul>
      <li>
        <a class="home-button" href="{% url 'problems_list:home' %}">
          Problems List
        </a>
      </li>
    </ul>
  </div>
</div>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block link %}
  {% endblock link %}
  
  {% block title %}
  {% endblock title %}
</head>
<body>
  {% block content %}
  {% endblock content %}
  
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  {% block script %}
  {% endblock script %}
</body>
</html>